# Segmagic Configuration File
# This file contains all configurable parameters for training and inference

[general]
name = "NFmouse_Segmagic"  # Project name for logging and organization
description = "Neurofilament segmentation in mouse tissue"

[data]
base_path = "L:/Robert Blum/GPU PC Backup/Annotations/NF_mouse/Segmagic"

[dataset]
labels = ['NF']
out_classes = ["cell"]
max_signal = 65536
different_pages = false
one_channel = true
channels = [0]
use_regions = false

[training]
epochs = 50